name: "FiveM Resource Watcher"
description: "Watches for changed resources and restarts them"
inputs:
  serverIP:
    description: "IP of the FiveM server"
    required: true
    default: ""
  serverPort:
    description: "Port of the FiveM server"
    required: false
    default: 30120
  rconPassword:
    description: "Password that you have set for rcon"
    required: true
    default: ""
  resourcesFolder:
    description: "Resources folder name"
    required: false
    default: "resources"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.serverIP }}
    - ${{ inputs.serverPort }}
    - ${{ inputs.rconPassword }}
    - ${{ inputs.resourcesFolder }}
